### ISSUE TITLE
Firebase integration

### ISSUE THREAD

**Issue by celsooliveiraTBDE** [celsooliveiraTBDE/street-art-finder#5]
Firebase will be the database where we store all data from APIs, pass it along to the Google APIs (maps and fusion).

**Comment by n0rthf4ce** [comment]
creates a new firebase object whenever a comment is posted related to a new flikr picture.
object will have properties:
unique ID-(pulled from flikr API)
latitude-(pulled from flikr API)
longitude-(pulled from flikr API)
picture URL-(pulled from flikr API)
comments object-(stored in firebase and dynamically manipulated via web app)

**Comment by n0rthf4ce** [comment]
generates firebase objects whenever a flikr query is initiated.  each picture will have a relevant object with:
unique ID-(pulled from flikr API)
latitude-(pulled from flikr API)
longitude-(pulled from flikr API)
picture URL-(pulled from flikr API)
comments object-(stored in firebase and dynamically manipulated via web app)

**Comment by n0rthf4ce** [comment]
deletes all the objects without a "comments object" upon page refresh
